#!/usr/bin/env node
/**
 * Generates SQL statements to seed the database with an initial user for
 * every role supported by the application (see `src/db/schema.ts`).
 *
 * All seeded users share the password below and are created with
 * `status: "active"` so they can sign in immediately.
 *
 * Usage:
 *   node scripts/seed-users.mjs > drizzle/seed/seed.sql
 *
 * The generated file is applied with `npm run db:seed` (see package.json),
 * which runs it against the local D1 database via wrangler (add `-- --remote`
 * to apply it to the remote/production database instead).
 */
import crypto from "node:crypto";
import { hashPassword } from "better-auth/crypto";

export const SEED_PASSWORD = "garland123";

export const SEED_USERS = [
  { email: "admin@example.com", name: "Admin User", role: "admin", status: "active" },
  { email: "partner@example.com", name: "Partner User", role: "partner", status: "active" },
];

function escapeSql(value) {
  return value.replace(/'/g, "''");
}

async function generate() {
  const now = Date.now();
  const statements = [
    "-- Auto-generated by scripts/seed-users.mjs. Do not edit by hand.",
    "-- Regenerate with: node scripts/seed-users.mjs > drizzle/seed/seed.sql",
  ];

  for (const user of SEED_USERS) {
    const userId = crypto.randomUUID();
    const accountId = userId;
    const passwordHash = await hashPassword(SEED_PASSWORD);

    statements.push(
      `INSERT INTO users (id, email, name, role, status, created_at, updated_at) VALUES ('${userId}', '${escapeSql(user.email)}', '${escapeSql(user.name)}', '${user.role}', '${user.status}', ${now}, ${now});`,
    );
    statements.push(
      `INSERT INTO accounts (id, user_id, account_id, provider_id, password, created_at, updated_at) VALUES ('${crypto.randomUUID()}', '${userId}', '${accountId}', 'credential', '${passwordHash}', ${now}, ${now});`,
    );
  }

  return statements.join("\n") + "\n";
}

generate().then((sql) => {
  process.stdout.write(sql);
});
